version: 0.2

env:
  variables:
    # ingen trailing slash / på din url!
    APP_URL: "http://vecka-15-eb-env.eba-w2kizkxr.eu-north-1.elasticbeanstalk.com" # här ska vår EB-url vara

# appen är redan live, vi behöver inte köra enhetstester med maven
phases:
  build:
    commands:
      # curl finns färdiginstallerat på AWS i CodeBuild
      - echo "Smoke test med curl"
      - HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$APP_URL/health")
      - echo "Fick HTTP $HTTP_CODE"
      - |
        if [ "$HTTP_CODE" != "200" ]; then
        echo "Smoke test FAILED: forvantade 200, fick $HTTP_CODE"
        exit 1
        fi
      - echo "Smoke test PASSED"